### ISSUE TITLE
Any way to change it into not uppercase and lowercase sensitive?

### ISSUE THREAD

**Issue by thepenguinthatwants** [windwp/rofi-color-picker#1]
Hi,
your tool is amazing, but sometimes it gets bit annoying if it cant find
green unless I rewrite to Green.

Any way to fix it?

**Comment by windwp** [comment]
Hm I don't have that problem. 
I think it is your rofi setting. my rofi always case sensitive in this tool and another application too.

**Comment by windwp** [comment]
I update it to use ignore case on this tool. Can you check it
